### ISSUE TITLE
Macro highlighting

### ISSUE THREAD

**Issue by alexheretic** [atom/language-rust#1]
I started to test this package since tree-sitter by default is coming soon. I'll raise issues as I encounter them, let me know if that isn't desired. Overall it's working pretty well. I'm getting used to the colour changes _the red field colours seem a bit much but I'll probably get used to it_.

Issue: Contrary to my expectation `!` symbol is not the same colour as the macro name.

![](https://user-images.githubusercontent.com/2331607/46614078-d6e24800-cb0c-11e8-8b01-ed87943f4598.png)

**Comment by maxbrunsfeld** [comment]
> the red field colors seem a bit much but I'll probably get used to it

You mean the field names in the struct definition? Yeah, it's probably a change from the old highlighting, but I really think it's an improvement, because fields now always appear in the same color: both when they're declared, and when they're referenced.

> Issue: Contrary to my expectation ! symbol is not the same colour as the macro name.

That's interesting; I kind of like the `!` *not* being highlighted in blue because I view at as not part of the macro's *name* (in this case, `println`), but rather part of Rust's macro-invocation syntax, like the delimiters. I'm not super strongly opinionated about this though; I could be talked into coloring the `!`.

**Comment by alexheretic** [comment]
> That's interesting; I kind of like the ! not being highlighted in blue because I view at as not part of the macro's name (in this case, println), but rather part of Rust's macro-invocation syntax, like the delimiters. I'm not super strongly opinionated about this though; I could be talked into coloring the !.

I see what you mean, and I don't disagree with that argument directly. But overall I'd still recommend colouring the ! for a couple of reasons. Firstly because this highlighting is used elsewhere.

### Rust documentation
![rust-doc-hl](https://user-images.githubusercontent.com/2331607/47149155-a9468d00-d2ca-11e8-81e7-d32db25ea0df.png)

### Intellij
![intellij-hl](https://user-images.githubusercontent.com/2331607/47149180-b95e6c80-d2ca-11e8-9571-76f6d6ce747a.png)

### vscode
![vscode-hl](https://user-images.githubusercontent.com/2331607/47149193-bebbb700-d2ca-11e8-8eb4-d60de27ddf69.png)

### Github markdown
```rust
println!("hello world");
```

---

Secondly, and more subjectively, I think it can help with the readability of some usages:

![not-matches](https://user-images.githubusercontent.com/2331607/47149419-6b963400-d2cb-11e8-898e-356e54d8e025.png)

**Comment by maxbrunsfeld** [comment]
Good points. I think you're right and we should change it.

**Comment by maxbrunsfeld** [comment]
Ok, I've done this in https://github.com/atom/atom/commit/2efd4ce3676e646247dab2d10b5a55e0b20e3867.
